import Head from "next/head";
import TeacherContainer from "../../src/containers/teacher/index";
import { Container } from "@nextui-org/react";
import { Switch, Spacer, Radio, Grid, Button } from "@nextui-org/react";
import Link from 'next/link'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container css={{mt: 16}}>
            <Grid.Container gap={2}>
          <Grid xs justify='center'>
            <Link href='/admin/FeeInfo'>
            <Button >
              Fee Data
            </Button>
            </Link>
          </Grid>
          <Grid xs justify='center'>
            <Link href='/admin/PayInfo'>
            <Button >
              Payments Data
            </Button></Link>
          </Grid>
          <Grid xs justify='center'>
            <Link href='.'>
            <Button >
              Create User
            </Button></Link>
          </Grid>
        </Grid.Container>
        </Container>
      </main>
    </>
  );
}
