import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";
import Screen from '../../src/containers/admin/PayInfo'
import { Container, Button } from "@nextui-org/react";
import LoginModal from "../../src/components/needsLoginModal";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Screen />
        </Container>
        <LoginModal />
      </main>
    </>
  );
}
