import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";
import "firebase/compat/auth";
import { doc, getDoc } from "firebase/firestore";
import InitializeFirebase from "../src/utils/firebase";
import { getFirestore } from "firebase/firestore";

import { Container, Button } from "@nextui-org/react";
const db = getFirestore(InitializeFirebase());


import LoginContainer from "../src/containers/login/index";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{background: 'rgb(128 128 128 / 25%)'}}>
        <Container css={{pt: 16, height: '100vh', display: 'flex',
justifyContent: 'space-around',
paddingTop: '5rem',}}>
      <LoginContainer />
        </Container>
      </main>
    </>
  );
}
