import Head from "next/head";
import StudentContainer from "../../src/containers/student/index";
import { Container } from "@nextui-org/react";
import * as xlsx from "xlsx";
import { useState } from "react";

export default function Home() {
  const [data, setData] = useState(undefined);
  const readUploadFile = (e) => {
    e.preventDefault();
    if (e.target.files) {
      const reader = new FileReader();
      reader.onload = (e) => {
        const data = e.target.result;
        const workbook = xlsx.read(data, { type: "array" });
        const sheetName = workbook.SheetNames[1];
        const worksheet = workbook.Sheets[sheetName];
        const json = xlsx.utils.sheet_to_json(worksheet);
        setData(json);
      };
      reader.readAsArrayBuffer(e.target.files[0]);
    }
  };

  var dataArray = data;
  var _IDandTimestampDataArray = [];
  var _formattedData = [];
  
  if (data) {
  dataArray.splice(0, 2);
    for (var i = 0; i < dataArray.length; i++) {
      if ((dataArray[i].__rowNum__ + 1) % 3 == 0) {
        _IDandTimestampDataArray.push(dataArray[i]["List of Logs"]);
      }
      if ((dataArray[i].__rowNum__ + 2) % 3 == 0) {
        _IDandTimestampDataArray.push(dataArray[i].__EMPTY_1);
      }
    }

    for (var i = 0; i < _IDandTimestampDataArray.length; i++) {
      if (i % 2 == 0) {
        _formattedData.push({ userId: _IDandTimestampDataArray[i], timestamps: _IDandTimestampDataArray[i + 1].split('\n') });
      }
    }
  }
    console.log(_formattedData);
    console.log((_formattedData.find(o => o.userId == '5')).timestamps)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <form>
          <label htmlFor="upload">Upload File</label>
          <input
            type="file"
            name="upload"
            id="upload"
            onChange={readUploadFile}
          />
        </form>
        {JSON.stringify(_formattedData)}
        {/* {console.log(array.join(", "))} */}
      </main>
    </>
  );
}
